### ISSUE TITLE
Working with themosis and SEOPress generated sitemap

### ISSUE THREAD

**Issue by romainhe** [wp-seopress/wp-seopress#1]
Hi, thx for your awesome new SEO plugin. I'm sick of yoast ^^
(We realy want to add your plugin in our workflow process with pro features)

### So, the problem now ^^

We use themosis, a wordpress framework that add many big features (custom routes, MVC, etc.)
We have a problem with the way your plugin works to display sitemap page. When we go to /sitemaps.xml we got an error that headers already sent, wordpress starting to display a "normal" page and your function start too, **cause your code is called too early in the process...**

I contact the framework author who confirm that, you can see the issue here : 
https://github.com/themosis/themosis/issues/186#issuecomment-332300270

Can you add a fix or a tips to fix that ? 

Thx a lot for your help !

**Comment by wp-seopress** [comment]
Hi,
I see your issue on GIT (received a Mention alert) this morning.
Can you send me your theme?
Thanks

**Comment by romainhe** [comment]
It's a themosis environnement : https://framework.themosis.com/docs/1.3/introduction/
My theme will not change anything to the issue...

If you want a working test env. you can grab the bookstor demo theme of themosis here https://github.com/themosis/bookstore

Thx !

**Comment by wp-seopress** [comment]
Go to wp-seopress/seopress.php, line 451 approximately, lower the value 9999 to 999 and see if it works.
Thanks
<img width="675" alt="" src="https://user-images.githubusercontent.com/30056254/30927372-8bbe40ee-a3b8-11e7-94e9-17b5f5c78f8d.png">

**Comment by romainhe** [comment]
I will try this, thx !

**Comment by romainhe** [comment]
Don't change anything... :(

**Comment by wp-seopress** [comment]
Too bad :(
I'll try to setup Themosis on my side to make some tests. 
No ETA to provide for now.

**Comment by romainhe** [comment]
ok thx, let me know if you need something

**Comment by wp-seopress** [comment]
Too bad :(
I'll try to setup Themosis on my side to make some tests. 
No ETA to provide for now.

**Comment by romainhe** [comment]
@wp-seopress Hi !

Themosis use template_redirect action for all routes, do you have any idea to adapt your template_include action with template_redirect ?

thx

**Comment by romainhe** [comment]
Here is a solution, simply include and exit instead of return template path
![image](https://user-images.githubusercontent.com/1837829/36381590-5f1b1a54-1586-11e8-91db-69008b8e342c.png)

**Comment by wp-seopress** [comment]
Thank you for the fix. Will include it in the next release if all tests are OK.

**Comment by romainhe** [comment]
@wp-seopress just noticed that I forgot a fix, seopress use the template_include action hook. For the fix to work, we must use template_redirect instead of template_include line 413 seopress_xml_sitemap_change_template function

`add_action( 'template_redirect', 'seopress_xml_sitemap_change_template', 1 );`

**Comment by romainhe** [comment]
Missed reopen issue...

**Comment by wp-seopress** [comment]
Fixed in 3.3.11
