### ISSUE TITLE
Open Graph options don't persist on frontend

### ISSUE THREAD

**Issue by JimmyHowe** [wp-seopress/wp-seopress#10]
Hey, updating the default image options doesn't work for facebook and twitter... I can update the option on the page, but the front end won't work. Manually going into the page and changing the images there will update.

**Comment by JimmyHowe** [comment]
Neither does the twitter tag either

**Comment by wp-seopress** [comment]
Hi,
can you share a URL of your page?
If I'm not mistaken, the order is as follows:
- featured image
- first image of your post content
- default image set in SEO > Social

**Comment by JimmyHowe** [comment]
Thanks for getting back ... Ah ok, sorry I completely overlooked the order of this, yeah that makes sense!
There was no featured image and was expecting it to fall to the default image.
