### ISSUE TITLE
[Feature request] Remove metaboxes from certain post types

### ISSUE THREAD

**Issue by srcek** [wp-seopress/wp-seopress#4]
Hi, is it possible to remove SEOPress metaboxes from certain post types. I can't find such option. If it's not available I'd like to propose this as feature request. 
For single post types, archives and taxonomies there should be an option not to display SEOPRess metabox in wp-admin.
Thank you.

**Comment by wp-seopress** [comment]
Hi,
you can do that with these hooks:

https://www.seopress.org/support/hooks/filter-seo-metaboxe-call-by-custom-taxonomy/
https://www.seopress.org/support/hooks/filter-structured-data-types-metaboxe-call-by-post-type/
https://www.seopress.org/support/hooks/filter-seo-metaboxe-call-by-post-type/

Best,
Benjamin

**Comment by srcek** [comment]
It would be nice to have that capability inside the wp-admin options (eg. Advanced -> Appearance) as a checkbox or select.
