### ISSUE TITLE
Cosmetic changes for better UX

### ISSUE THREAD

**Issue by oppenheimer-** [wp-seopress/wp-seopress#6]
Salut Ben!

Just a small nuisance with my PRO installation and the even the website.

I see that you have a faible for thin font-weights (300) in the backend and light colored type on a white background on your website. Sadly, my eyes are getting worse and i have a hard time reading these texts; especially the nav-bar is a pain.

Please consider this quick fix in the next version. Merci!

**Comment by wp-seopress** [comment]
C'est prévu :)

**Comment by oppenheimer-** [comment]
I'm on windows and the font defaults to "Segoe UI" which is really hard to read at font-weight 300 at 14px. Maybe drop the specific font-weight setting or use your very own localized Webfont.

Just to illustrate of what i mean:
![image](https://user-images.githubusercontent.com/10992675/50547813-0d2df000-0c42-11e9-8f51-8ca1ab997591.png)
![image](https://user-images.githubusercontent.com/10992675/50547771-ee7b2980-0c40-11e9-9110-66e1e6c0e30b.png)

**Comment by wp-seopress** [comment]
Fixed in 3.3.1.
ETA: soon ;)
